# Generated by Django 2.1 on 2019-02-10 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctgctg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='block',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='members',
            name='intercom_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='scores',
            name='score',
            field=models.PositiveIntegerField(),
        ),
    ]
