# Generated by Django 2.1 on 2019-02-10 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ctgctg', '0002_auto_20190210_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='name',
        ),
        migrations.AddField(
            model_name='members',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
