# Generated by Django 2.1 on 2019-02-10 08:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ctgctg', '0003_auto_20190210_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
