# Generated by Django 2.1 on 2019-02-10 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ctgctg', '0004_auto_20190210_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='user',
        ),
    ]
