# Generated by Django 2.1 on 2019-02-11 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ctgctg', '0005_remove_members_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='block',
        ),
        migrations.RemoveField(
            model_name='members',
            name='flat_number',
        ),
        migrations.RemoveField(
            model_name='members',
            name='intercom_number',
        ),
        migrations.RemoveField(
            model_name='members',
            name='last_played',
        ),
    ]
