# Generated by Django 2.1 on 2019-02-12 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ctgctg', '0009_auto_20190212_1352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='members',
            old_name='user',
            new_name='username',
        ),
    ]
