# Generated by Django 2.1 on 2019-03-25 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ctgctg', '0013_auto_20190325_1944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='File',
            new_name='Image',
        ),
    ]
