# Generated by Django 2.1 on 2019-03-26 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctgctg', '0016_post_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_slug',
            field=models.SlugField(default='hi'),
        ),
    ]
