# Generated by Django 2.1 on 2019-03-26 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctgctg', '0017_post_title_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_comments',
            name='comment',
            field=models.TextField(),
        ),
    ]
