# Generated by Django 2.1 on 2019-03-26 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctgctg', '0018_auto_20190326_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Song_Name', models.CharField(max_length=256)),
                ('Artist_Name', models.CharField(max_length=256)),
                ('Genre', models.CharField(max_length=95)),
                ('Song_File', models.FileField(upload_to='')),
                ('Cover_Picture', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
