# Generated by Django 2.1 on 2019-03-26 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ctgctg', '0020_music_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='Artist_Name',
        ),
        migrations.RemoveField(
            model_name='music',
            name='Cover_Picture',
        ),
        migrations.RemoveField(
            model_name='music',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='music',
            name='Genre',
        ),
        migrations.RemoveField(
            model_name='music',
            name='Song_File',
        ),
        migrations.RemoveField(
            model_name='music',
            name='Song_Name',
        ),
    ]
