# Generated by Django 2.1 on 2019-03-26 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ctgctg', '0021_auto_20190326_2011'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Music',
        ),
    ]
