# Generated by Django 2.1 on 2019-03-26 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ctgctg', '0022_delete_music'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Song_Name', models.CharField(max_length=256)),
                ('Artist_Name', models.CharField(max_length=256)),
                ('Genre', models.CharField(max_length=95)),
                ('Song_File', models.FileField(upload_to='')),
                ('Cover_Picture', models.ImageField(blank=True, upload_to='')),
                ('Description', models.TextField(blank=True)),
                ('user_uploaded', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
