# Generated by Django 2.1 on 2019-03-27 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctgctg', '0025_music'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='Cover_Picture',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
