# Generated by Django 2.1.7 on 2021-06-08 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EndCOv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='Image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
