# Generated by Django 2.1.7 on 2021-06-08 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EndCOv', '0002_auto_20210608_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='Image',
            field=models.ImageField(upload_to='EndCOv/media'),
        ),
    ]
